INSERT INTO items (title, description, imageurl) VALUES ('Flute', 'Like-new flute to lend. Cmon, you know you want to play it...','https://firebasestorage.googleapis.com/v0/b/boomtown-dfdd8.appspot.com/o/demo-images%2Fflute.jpg?alt=media');
INSERT INTO items (title, description, imageurl) VALUES ('Hatchet', 'Chop things down, show nature who is boss. But be safe—alcoholic beverage not included..','https://firebasestorage.googleapis.com/v0/b/boomtown-dfdd8.appspot.com/o/demo-images%2Fhatchet.jpg?alt=media');
INSERT INTO items (title, description, imageurl) VALUES ('Mix-Tape', 'What is on it? Who knows! Borrow it and find out. Tape deck not included.','https://firebasestorage.googleapis.com/v0/b/boomtown-dfdd8.appspot.com/o/demo-images%2Fmix-tape.jpg?alt=media');
INSERT INTO items (title, description, imageurl) VALUES ('Learn To Code Books', 'Learn HTML, CSS, JavaScript, and jQuery in 800 pages or less.','https://firebasestorage.googleapis.com/v0/b/boomtown-dfdd8.appspot.com/o/demo-images%2Fcode-books.jpg?alt=media');
INSERT INTO items (title, description, imageurl) VALUES ('Keyboard', 'Teach your cat to tickle these elephant-friendly (plastic) ivories.','https://firebasestorage.googleapis.com/v0/b/boomtown-dfdd8.appspot.com/o/demo-images%2Fkeyboard.jpg?alt=media');
INSERT INTO items (title, description, imageurl) VALUES ('Baseball', 'Lightly-used baseball for you and your friend to enjoy at your next ball tournament.','https://firebasestorage.googleapis.com/v0/b/boomtown-dfdd8.appspot.com/o/demo-images%2Fbaseball.jpg?alt=media');
INSERT INTO items (title, description, imageurl) VALUES ('Skateboard', 'Relive your youth! And try not to seriously injure yourself while doing it!','https://firebasestorage.googleapis.com/v0/b/boomtown-dfdd8.appspot.com/o/demo-images%2Fskateboard.jpg?alt=media');
INSERT INTO items (title, description, imageurl) VALUES ('Iron and Ironing Board', 'Dress for the job you want, not the one you have, with freshly pressed shirts and slacks.','https://firebasestorage.googleapis.com/v0/b/boomtown-dfdd8.appspot.com/o/demo-images%2Firon-and-board.jpg?alt=media');

INSERT INTO tags(title) VALUES('Household Items'),('Recreational Equipment'), ('Electronics'), ('Tools'),('Musical Instruments'),('Physical Media'), ('Sporting Goods');
INSERT INTO itemtags(itemid, tagid) VALUES (1,1), (2,1),(2,2),(3,5),(4,4),(5,6),(6,6),(7,5),(8,2),(8,7),(9,7);
